try:
    from ..models import GPTAssistant
except ImportError:
    # Running as script, use absolute import
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from models import GPTAssistant



guidelines = """
        1. **Annotate every occurrence** of an authority, including abbreviated forms.
        2. Use the same `docid` for all mentions of the same authority within the same document.
        3. Apply a general tag first, then apply specific tags inside it.
        4. Consider fragments as part of the same mention only if they are ≤ 2 stop-words away from the title/reference/source. Otherwise, create a new mention with the same `docid`.

        ### Global Annotation Structure:

        Each mention should follow this structure:

        ```
        <auto_label labelname=AUTHORITY_TYPE docid="...">
            <auto_label labelname="title" titletype="official|alias">...</auto_label>
            <auto_label labelname="reference">...</auto_label>        (legislation/decisions only)
            <auto_label labelname="authors">...</auto_label>            (secondary sources only)
            <auto_label labelname="source">...</auto_label>              (secondary sources only)
            <auto_label labelname="fragment" fragmentid="..." non_standard="true|false">...</auto_label>
        </auto_label>
        ```

        Include only the elements that are present in the text.

        ---

        ### Specific Annotation Instructions:

        #### 1. Legislation:

        - **Wrap the entire mention** in `<auto_label labelname="legislation">`.
        - Assign a manual `docid` using a short, stable identifier.

        ##### Examples of `docid`:

        - IRPA → Immigration and Refugee Protection Act
        - Charter → Canadian Charter of Rights and Freedoms

        ##### Titles:

        - Tag the law name as `<auto_label labelname="title">`.
        - `titletype="official"` for full legal title
        - `titletype="alias"` for acronyms, short names, “the Act”

        ##### References:

        - Tag statute citations as `<auto_label labelname="reference">`.

        ##### Fragments:

        - Use standard fragment IDs (e.g., `sec 1`, `subsec 1(1)`) or set `non_standard=true` for non-standard formats.

        #### 2. Decisions:

        - **Wrap each mention** in `<auto_label labelname="decision">`.
        - Assign a short, distinctive `docid`.

        ##### Titles:

        - Use `<auto_label labelname="title">` with `titletype="official"` for full citation and `titletype="alias"` for short form.

        ##### References:

        - Each citation is tagged as its own `<auto_label labelname="reference">`.
        ##### Fragments:

        - Use `p` for pages and `para` for paragraphs, including both bounds for intervals.

        #### 3. Secondary Sources:

        - **Wrap each mention** in `<auto_label labelname="secondary_sources">`.
        - `docid` should be a short, distinctive title.

        ##### Titles:

        - Tag with `<auto_label labelname="title">` for books, articles, or contributions.

        ##### Authors:

        - Include all authors in one `<auto_label labelname="authors">` tag.
        ##### Source:

        - Tag journal/publisher/year/volume/starting page in `<auto_label labelname="source">`.

        ##### Fragments:

        - Use formats like `p 127` or `no 1958` for pages and paragraphs.

        #### 4. Unable to Classify:

        - Use `<auto_label labelname="unable_to_classify">` only if the source is unclear or borderline.
        - Assign a `docid` regardless.

        ---

        ### Edge Cases and Error Handling:

        - Annotate separately if laws incorporate other laws.
        - Each constitutional text must be distinct under `<auto_label labelname="legislation">`.
        - Different courts for the same parties should have different `docid`s.
        - When encountering non-standard fragments, clearly reproduce the format.

        """

def get_meta_prompt(annotation_guidelines, model_name="gpt-4o", temperature=0.7):
    """
    Use a meta-LLM to generate the perfect prompt for the annotation LLM.
    
    Args:
        annotation_guidelines: String containing the annotation guidelines/rules
        model_name: The model to use for generating the meta prompt
        temperature: Temperature for the meta-LLM generation
    
    Returns:
        str: The optimized system prompt generated by the meta-LLM
    """
    # Initialize the meta-LLM
    meta_llm = GPTAssistant(model_name=model_name, temperature=temperature)
    
    # System prompt for the meta-LLM
    system_prompt = """
    You are an expert in prompt engineering for legal document annotation systems.
    
    Your task is to create the perfect system prompt for an LLM that will automatically annotate legal texts. 
    The annotation LLM needs clear, precise instructions to understand:
    - What to annotate
    - How to annotate (using the correct XML schema)
    - What rules to follow
    - What to avoid
    
    You will receive annotation guidelines. Based on these guidelines, create a comprehensive, 
    clear, and effective system prompt that will make the annotation LLM perform optimally.
    
    The prompt should be:
    - Detailed and specific
    - Include all necessary rules and constraints
    - Provide clear examples of the annotation schema
    - Explain edge cases and error handling
    - Be structured and easy to follow
    
    Output ONLY the system prompt text that will be used for the annotation LLM, without any meta-commentary.
    """
    
    # User prompt for the meta-LLM
    user_prompt = f"""
    Here are the annotation guidelines for the legal text annotation task:
    
    {annotation_guidelines}
    
    Based on these guidelines, create the optimal system prompt for the annotation LLM.
    """
    
    # Generate the meta prompt
    generated_prompt = meta_llm.generate(system_prompt, user_prompt)
    
    return generated_prompt

def get_prompt_processing(few_shot_examples=None):
    """
    Create system and user prompts for the AI model to process legal text.
    
    Args:
        few_shot_examples: List of tuples (input, expected_output) for few-shot learning
    
    Returns:
        tuple: (system_prompt, user_prompt_template)
    """
    system_prompt = f"""
        You are an advanced Language Model designed to annotate legal texts by identifying and marking mentions of legal authorities in Canadian legal decisions. Follow these detailed instructions to ensure accurate and consistent annotations:

        ---

        ### Task Objective:

        Identify and annotate every mention of legal authorities, including both complete and partial references, in the text using the specified XML schema.

        ### Authority Types:

        Each mention must be categorized into one of the following authority types:
        - `<auto_label labelname="legislation">`: Statutes, codes, constitutional texts
        - `<auto_label labelname="decision">`: Judicial or administrative decisions
        - `<auto_label labelname="secondary_sources">`: Doctrine, books, articles, reports, dictionaries
        - `<auto_label labelname="unable_to_classify">`: Ambiguous sources that may be borderline law vs. fact

        ### Core Annotation Principles:

        {guidelines}

        ---

        Follow these guidelines meticulously to ensure accurate and consistent legal text annotations.

        """
    
    # Add few-shot examples if provided
    if few_shot_examples:
        system_prompt += "\n\nHere are some examples:\n"
        for i, (input_text, expected_output) in enumerate(few_shot_examples, 1):
            system_prompt += f"\nExample {i}:\n"
            system_prompt += f"<<<ORIGINAL_TEXT>>>{input_text}<<<END_ORIGINAL_TEXT>>>\n"
            system_prompt += f"<<<EXPECTED_OUTPUT>>>{expected_output}<<<END_EXPECTED_OUTPUT>>>\n"
    
    user_prompt_template = """Please annotate the following legal text with the appropriate auto_label tags:

    <<<ORIGINAL_TEXT>>>{text}<<<END_ORIGINAL_TEXT>>>
    
    OUTPUT:"""
    
    return system_prompt, user_prompt_template

def get_prompt_fallback_consistency():
    """
    Create system and user prompts for the AI model to save consistency errors.
        
    Returns:
        tuple: (system_prompt, user_prompt_template)
    """
    system_prompt = f"""
        You are a legal assistant specialized in automatic annotation of legal texts. Your role is to correct errors in previously annotated texts.

        You will receive :
        1. The Original text.
        2. A version of the text annotated with <auto_label> tags that contains at least one error of consistency. 
        
        A consistency error means that some oppening <auto_label> tags or closing </auto_label> tags are missing. 
        The oppening tag count doesn't match the closing tag count.



        You must carefully detect where the missing <auto_label> is missing and correct the issue while respecting the annotation schema below.

        ### Core Annotation Principles:

        {guidelines}

        ---

        Follow these guidelines meticulously to ensure accurate and consistent legal text annotations.
    """
    
    
    user_prompt_template = """Please correct the annotated text to fix any discrepancies with the original text while adhering to the annotation schema:

    Input: "{text_pair}"
    
    Output:"""
    
    return system_prompt, user_prompt_template

def get_prompt_fallback_hallucination():
    """
    Create system and user prompts for the AI model to save hallucination errors.
        
    Returns:
        tuple: (system_prompt, user_prompt_template)
    """
    system_prompt = """
        You are a legal assistant specialized in automatic annotation of legal texts. Your role is to correct errors in previously annotated texts.

        You will receive:
        1. The original text.
        2. A version of the text annotated with <auto_label> tags that contains at least one error.

        The upstream error-detection system compares the original text and the annotated text token by token. After removing all <auto_label> tags, both token lists must match exactly. When they do not, the text pair is sent to you for correction.

        Typical error patterns include:
        - Incorrect annotation boundaries at the beginning or end of a labeled span.
        - Added or removed quotation marks.
        - Added or removed spaces or line breaks.

        You must carefully correct these issues while respecting the annotation schema below.

        ### Core Annotation Principles:

        {guidelines}

        ---

        Follow these guidelines meticulously to ensure accurate and consistent legal text annotations.
    """
    
    
    user_prompt_template = """Please correct the annotated text to fix any discrepancies with the original text while adhering to the annotation schema:

    Input: "{text_pair}"
    
    Output:"""
    
    return system_prompt, user_prompt_template








if __name__ == "__main__":
    # Example usage - read annotation guidelines from file
    guidelines_path = r"C:\Users\zakga\OneDrive\Documents\code\labelstudio\annotation\ressources\llm_AG.md"
    
    with open(guidelines_path, 'r', encoding='utf-8') as f:
        annotation_guidelines = f.read()
    
    meta_prompt = get_meta_prompt(annotation_guidelines)
    print("Generated Meta Prompt:\n", meta_prompt)