from utils_extraction.html_utils import extract_body, is_manual_label_tag, is_auto_label_tag, is_tag_token, clean_html_formatting
from utils_extraction.processing_utils import distance_lists_auto_label,  check_auto_label_consistency, apply_operations_safe
from utils_extraction.tokenizer_utils import tokenize, decode
from utils_extraction.html_cleaner import clean_tokens
from utils_extraction.chunker_utils import chunk_tokens, flatten_token_chunks
from utils_extraction.few_shot_utils import extract_few_shot_examples, prepare_label_tokens, select_few_shot
from utils_extraction.prompt_utils import get_prompt_fallback_consistency, get_prompt_fallback_hallucination, get_prompt_processing
from utils_extraction.htmlLabel import HTMLLabel, from_simplified
from utils_extraction.chunck_level_post_processing import apply_post_processing_transforms
from utils_extraction.verification_utils import verify_processed_chunk, check_hallucination, check_consistency, check_label_scheme, VerificationResult, LABEL_SCHEME
from utils_extraction.document_level_post_processing_utils import merge_tokens_with_auto_labels, add_style_and_parent_to_auto_labels, compare_html_allow_auto_labels