from .prompts.sublabel_definitions import SUBLABEL_DEFINITIONS
from .prompts.guidelines import ANNOTATION_GUIDELINES   




def get_meta_prompt(annotation_guidelines, model_name="gpt-4o", temperature=0.7):
    """
    Use a meta-LLM to generate the perfect prompt for the annotation LLM.
    
    Args:
        annotation_guidelines: String containing the annotation guidelines/rules
        model_name: The model to use for generating the meta prompt
        temperature: Temperature for the meta-LLM generation
    
    Returns:
        str: The optimized system prompt generated by the meta-LLM
    """
    # Initialize the meta-LLM
    meta_llm = GPTAssistant(model_name=model_name, temperature=temperature)
    
    # System prompt for the meta-LLM
    system_prompt = """
    You are an expert in prompt engineering for legal document annotation systems.
    
    Your task is to create the perfect system prompt for an LLM that will automatically annotate legal texts. 
    The annotation LLM needs clear, precise instructions to understand:
    - What to annotate
    - How to annotate (using the correct XML schema)
    - What rules to follow
    - What to avoid
    
    You will receive annotation guidelines. Based on these guidelines, create a comprehensive, 
    clear, and effective system prompt that will make the annotation LLM perform optimally.
    
    The prompt should be:
    - Detailed and specific
    - Include all necessary rules and constraints
    - Provide clear examples of the annotation schema
    - Explain edge cases and error handling
    - Be structured and easy to follow
    
    Output ONLY the system prompt text that will be used for the annotation LLM, without any meta-commentary.
    """
    
    # User prompt for the meta-LLM
    user_prompt = f"""
    Here are the annotation guidelines for the legal text annotation task:
    
    {annotation_guidelines}
    
    Based on these guidelines, create the optimal system prompt for the annotation LLM.
    """
    
    # Generate the meta prompt
    generated_prompt = meta_llm.generate(system_prompt, user_prompt)
    
    return generated_prompt

def get_prompt_processing(prompt_path,few_shot_examples=None):
    """
    Create system and user prompts for the AI model to process legal text.
    
    Args:
        few_shot_examples: List of tuples (input, expected_output) for few-shot learning
    
    Returns:
        tuple: (system_prompt, user_prompt_template)
    """
    with open(prompt_path, 'r', encoding='utf-8') as f:
        system_prompt = f.read()
        
    
    # Add few-shot examples if provided
    if few_shot_examples:
        system_prompt += "\n\nHere are some examples:\n"
        for i, (input_text, expected_output) in enumerate(few_shot_examples, 1):
            system_prompt += f"\nExample {i}:\n"
            system_prompt += f"<ORIGINAL_TEXT>{input_text}<END_ORIGINAL_TEXT>\n"
            system_prompt += f"<EXPECTED_OUTPUT>{expected_output}<END_EXPECTED_OUTPUT>\n"
    
    user_prompt_template = """Please annotate the following legal text with the appropriate auto_label tags:

    <ORIGINAL_TEXT>{text}<END_ORIGINAL_TEXT>
    
    OUTPUT:"""
    
    return system_prompt, user_prompt_template




def build_sublabel_definitions(keep_labels):
    missing = [lbl for lbl in keep_labels if lbl not in SUBLABEL_DEFINITIONS]
    if missing:
        raise ValueError(f"Unknown sublabels: {missing}")

    return "\n".join(
        f"- {SUBLABEL_DEFINITIONS[label]}"
        for label in keep_labels
    )

def get_prompt_sublabel_extraction(prompt_path, keep_labels, few_shot_examples=None):
    """
    Generate dynamic prompt for sublabel extraction using a TXT template.

    Args:
        keep_labels (List[str]): Sublabels to extract (e.g. ["title", "citation"])

    Returns:
        Tuple[str, str]: (system_prompt, user_prompt_template)
    """

    with open(prompt_path, 'r', encoding='utf-8') as f:
        template = f.read()

    # --- Build dynamic fields ---
    sublabels_str = ", ".join(keep_labels)
    sublabels_definition = build_sublabel_definitions(keep_labels)

    # --- Fill template ---
    system_prompt = template.format(
        sublabels=sublabels_str,
        sublabels_definition=sublabels_definition,
    )

    # Add few-shot examples if provided
    if few_shot_examples:
        system_prompt += "\n\nHere are some examples:\n"
        for i, (input_text, expected_output) in enumerate(few_shot_examples, 1):
            system_prompt += f"\nExample {i}:\n"
            system_prompt += f"<ORIGINAL_TEXT>{input_text}<END_ORIGINAL_TEXT>\n"
            system_prompt += f"<EXPECTED_OUTPUT>{expected_output}<END_EXPECTED_OUTPUT>\n"
    
    user_prompt_template = """Please annotate the following legal text with the appropriate sublabels tags:

    <ORIGINAL_TEXT>{text}<END_ORIGINAL_TEXT>
    
    OUTPUT:"""

    return system_prompt, user_prompt_template




if __name__ == "__main__":

    try:
        from ..models import GPTAssistant
    except ImportError:
        # Running as script, use absolute import
        import sys
        from pathlib import Path
        sys.path.insert(0, str(Path(__file__).parent.parent))
        from ..models import GPTAssistant
    # Example usage - read annotation guidelines from file
    guidelines_path = r"C:\Users\zakga\OneDrive\Documents\code\labelstudio\annotation\ressources\llm_AG.md"
    
    with open(guidelines_path, 'r', encoding='utf-8') as f:
        annotation_guidelines = f.read()
    
    meta_prompt = get_meta_prompt(annotation_guidelines)
    print("Generated Meta Prompt:\n", meta_prompt)