from .prompts.sublabel_definitions import SUBLABEL_DEFINITIONS_V1, SUBLABEL_DEFINITIONS_V2
from .prompts.guidelines import ANNOTATION_GUIDELINES   
from .tokenizer_utils import decode



def get_meta_prompt(annotation_guidelines, model_name="gpt-4o", temperature=0.7):
    """
    Use a meta-LLM to generate the perfect prompt for the annotation LLM.
    
    Args:
        annotation_guidelines: String containing the annotation guidelines/rules
        model_name: The model to use for generating the meta prompt
        temperature: Temperature for the meta-LLM generation
    
    Returns:
        str: The optimized system prompt generated by the meta-LLM
    """
    # Initialize the meta-LLM
    meta_llm = GPTAssistant(model_name=model_name, temperature=temperature)
    
    # System prompt for the meta-LLM
    system_prompt = """
    You are an expert in prompt engineering for legal document annotation systems.
    
    Your task is to create the perfect system prompt for an LLM that will automatically annotate legal texts. 
    The annotation LLM needs clear, precise instructions to understand:
    - What to annotate
    - How to annotate (using the correct XML schema)
    - What rules to follow
    - What to avoid
    
    You will receive annotation guidelines. Based on these guidelines, create a comprehensive, 
    clear, and effective system prompt that will make the annotation LLM perform optimally.
    
    The prompt should be:
    - Detailed and specific
    - Include all necessary rules and constraints
    - Provide clear examples of the annotation schema
    - Explain edge cases and error handling
    - Be structured and easy to follow
    
    Output ONLY the system prompt text that will be used for the annotation LLM, without any meta-commentary.
    """
    
    # User prompt for the meta-LLM
    user_prompt = f"""
    Here are the annotation guidelines for the legal text annotation task:
    
    {annotation_guidelines}
    
    Based on these guidelines, create the optimal system prompt for the annotation LLM.
    """
    
    # Generate the meta prompt
    generated_prompt = meta_llm.generate(system_prompt, user_prompt)
    
    return generated_prompt

def get_prompt_processing(prompt_path, few_shot_examples=None, chunks=None, dynamic_few_shot_selection=False):
    """
    Create system and user prompts for the AI model to process legal text.

    Args:
        prompt_path              : path to the base system prompt file
        few_shot_examples        : - static mode : list of (input, output) tuples
                                   - dynamic mode: list of lists of (input, output) tuples,
                                     one inner list per chunk
                                     e.g. few_shot_examples[chunk_i][example_j] = (input, output)
        chunks                   : list of decoded chunk texts (required in dynamic mode)
        dynamic_few_shot_selection: if True, returns one prompt pair per chunk

    Returns:
        - static mode  : (system_prompt: str,       user_prompt_template: str)
        - dynamic mode : (system_prompts: list[str], user_prompts: list[str])
    """
    with open(prompt_path, 'r', encoding='utf-8') as f:
        base_system_prompt = f.read()

    def _build_system_prompt(base, examples):
        prompt = base
        if examples:
            prompt += "\n\nHere are some examples:\n"
            for i, (input_text, expected_output) in enumerate(examples, 1):
                prompt += f"\nExample {i}:\n"
                prompt += f"<ORIGINAL_TEXT>{input_text}<END_ORIGINAL_TEXT>\n"
                prompt += f"<EXPECTED_OUTPUT>{expected_output}<END_EXPECTED_OUTPUT>\n"
        return prompt

    def _build_user_prompt(text):
        return (
            "Please annotate the following legal text with the appropriate auto_label tags:\n\n"
            f"<ORIGINAL_TEXT>{text}<END_ORIGINAL_TEXT>\n\n"
            "OUTPUT:"
        )

    # ── DYNAMIC MODE ──────────────────────────────────────────────────────────
    if dynamic_few_shot_selection:
        if chunks is None:
            raise ValueError("`chunks` must be provided when dynamic_few_shot_selection=True")
        if few_shot_examples is None or len(few_shot_examples) != len(chunks):
            raise ValueError("`few_shot_examples` must have one entry per chunk in dynamic mode")

        system_prompts = [
            _build_system_prompt(base_system_prompt, few_shot_examples[i])
            for i in range(len(chunks))
        ]
        user_prompts = [
            _build_user_prompt(decode(chunk))
            for chunk in chunks
        ]
        return system_prompts, user_prompts

    # ── STATIC MODE ───────────────────────────────────────────────────────────
    system_prompt = _build_system_prompt(base_system_prompt, few_shot_examples)
    user_prompt_template = (
        "Please annotate the following legal text with the appropriate auto_label tags:\n\n"
        "<ORIGINAL_TEXT>{text}<END_ORIGINAL_TEXT>\n\n"
        "OUTPUT:"
    )
    return system_prompt, user_prompt_template




def build_sublabel_definitions(keep_labels, sublabel_definitions=SUBLABEL_DEFINITIONS_V1):
    missing = [lbl for lbl in keep_labels if lbl not in sublabel_definitions]
    if missing:
        raise ValueError(f"Unknown sublabels: {missing}")

    return "\n".join(
        f"- {sublabel_definitions[label]}"
        for label in keep_labels
    )

def get_prompt_sublabel_extraction(prompt_path, keep_labels, few_shot_examples=None, sublabel_definitions=SUBLABEL_DEFINITIONS_V1, with_context_bool=True):
    """
    Generate dynamic prompt for sublabel extraction using a TXT template.

    Args:
        keep_labels (List[str]): Sublabels to extract (e.g. ["title", "citation"])

    Returns:
        Tuple[str, str]: (system_prompt, user_prompt_template)
    """

    with open(prompt_path, 'r', encoding='utf-8') as f:
        template = f.read()

    # --- Build dynamic fields ---
    sublabels_str = ", ".join(keep_labels)
    sublabels_definition = build_sublabel_definitions(keep_labels, sublabel_definitions=sublabel_definitions)

    # --- Fill template ---
    system_prompt = template.format(
        sublabels=sublabels_str,
        sublabels_definition=sublabels_definition,
    )

    # Add few-shot examples if provided
    if few_shot_examples:
        system_prompt += "\n\nHere are some examples:\n"
        for i, (input_text, expected_output) in enumerate(few_shot_examples, 1):
            system_prompt += f"\nExample {i}:\n"
            system_prompt += f"<ORIGINAL_TEXT>{input_text}<END_ORIGINAL_TEXT>\n"
            system_prompt += f"<EXPECTED_OUTPUT>{expected_output}<END_EXPECTED_OUTPUT>\n"
    
    if with_context_bool:
        user_prompt_template = """Here is the legal context to consider for annotation:\n{context}\n\nNow, please annotate the following legal text with the appropriate sublabels tags:"""
    else:
        user_prompt_template = """Please annotate the following legal text with the appropriate sublabels tags:"""

    user_prompt_template += """

    <ORIGINAL_TEXT>{text}<END_ORIGINAL_TEXT>
    
    OUTPUT:"""

    return system_prompt, user_prompt_template




if __name__ == "__main__":

    try:
        from ..models import GPTAssistant
    except ImportError:
        # Running as script, use absolute import
        import sys
        from pathlib import Path
        sys.path.insert(0, str(Path(__file__).parent.parent))
        from ..models import GPTAssistant
    # Example usage - read annotation guidelines from file
    guidelines_path = r"C:\Users\zakga\OneDrive\Documents\code\labelstudio\annotation\ressources\llm_AG.md"
    
    with open(guidelines_path, 'r', encoding='utf-8') as f:
        annotation_guidelines = f.read()
    
    meta_prompt = get_meta_prompt(annotation_guidelines)
    print("Generated Meta Prompt:\n", meta_prompt)